### ISSUE TITLE
Dropped callback not being called. 

### ISSUE THREAD

**Issue by damarisz** [JimLiu/angular-ui-tree#272]
The dropped callback is not working. $scope.list is being updated when I drag the nodes, but when I try to intercept the dropped event, the code inside callback function is not being called.

Example: The following code will not print out anything.

dropped: function(event) {
            console.log(event.source.nodeScope.$modelValue);     
        }

**Comment by damarisz** [comment]
I am only using one tree:

```html
<div ui-tree callbacks="treeOptions" id="tree-root">
          <ol ui-tree-nodes ng-model="data">
            <li class="treeItem" ng-repeat="item in data" ui-tree-node ng-include="'nodes_renderer.html'"></li>
          </ol>
        </div>
```

and then in my JS code:
```javascript
$scope.treeOptions = {
      dropped: function(event) {
        console.log('dropped', event);
      }
    };
```

And dropped is not being called.

**Comment by damarisz** [comment]
Commit  f1507f7 fixes this issue :) although I had to manually fix that one line that was changed.

**Comment by bostondevin** [comment]
Solved my issue!
